# Generated by Django 4.1.3 on 2023-07-09 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinks',
            old_name='price',
            new_name='drink_price',
        ),
    ]
